# Generated by Django 3.1.1 on 2020-09-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200903_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='if_staff',
            field=models.BooleanField(default=False),
        ),
    ]
