# Generated by Django 3.1 on 2020-09-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_remove_friends_friend'),
        ('users', '0005_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(to='friends.Friends'),
        ),
    ]
