# Generated by Django 3.1 on 2020-09-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_friends_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='city',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='friends',
            name='last_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='friends',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='friends',
            name='status',
            field=models.TextField(blank=True),
        ),
    ]
