# Generated by Django 3.1.1 on 2020-09-03 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_if_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='if_staff',
            new_name='is_staff',
        ),
    ]
